#!/usr/bin/env python3
"""Rock Corpus vocal lines. Preserve source onsets; offsets are estimated.
Source method: process-mel5 uses min(1 bar, inter-onset interval).
Timed NLT seconds are retained (tempo=60), including tempo changes and gaps.
"""
import argparse, hashlib, json, math, statistics, zipfile
from pathlib import Path

def convert(raw, entry):
    rows=[]
    for line in raw.decode().splitlines():
        parts=line.split()
        if len(parts)!=4: raise ValueError(f'Invalid NLT row: {line}')
        sec,bar,pitch,degree=map(float,parts)
        assert all(map(math.isfinite,(sec,bar,pitch,degree))) and pitch.is_integer()
        rows.append((sec,bar,int(pitch)))
    assert len(rows)>=12 and all(b[0]>a[0] for a,b in zip(rows,rows[1:]))
    # Seconds-per-bar from source timing; used only to estimate articulation.
    ratios=[(b[0]-a[0])/(b[1]-a[1]) for a,b in zip(rows,rows[1:]) if b[1]>a[1]]
    typical=statistics.median(ratios);events=[];origin=rows[0][2];preview=0
    for i,(sec,bar,pitch) in enumerate(rows):
        if i+1<len(rows):
            nextsec,nextbar,_=rows[i+1];gap=nextsec-sec
            barsec=gap/(nextbar-bar) if nextbar>bar else typical
            duration=min(gap,barsec)
        else: gap=duration=min(typical/4,1)
        events.append([pitch-origin,round(duration,6)])
        if gap-duration>1e-6: events.append([None,round(gap-duration,6)])
        if bar-rows[0][1]<8: preview=len(events)
    # Validate every sounding onset and MIDI against the downloaded source.
    cursor=0;actual=[]
    for pitch,duration in events:
        assert duration>0
        if pitch is not None: actual.append((cursor,pitch+origin))
        cursor+=duration
    assert len(actual)==len(rows)
    assert all(abs(a[0]-(b[0]-rows[0][0]))<.001 and a[1]==b[2] for a,b in zip(actual,rows))
    name=entry['id'].replace('_',' ').title().replace('Jude','Jude')
    names={'satisfaction':'(I Can’t Get No) Satisfaction','sweet_child_o_mine':'Sweet Child O’ Mine','california_dreamin':'California Dreamin’','a_hard_days_night':'A Hard Day’s Night','free_fallin':'Free Fallin’'}
    return dict(id='rock-'+entry['id'].replace('_','-'),name=names.get(entry['id'],name),aliases=[entry['id'].replace('_',' ')],genre='rock',events=events,tempo=60,preview=preview,firstMidi=origin,measures=math.ceil(rows[-1][1]-rows[0][1])+1,source='Rock Corpus — de Clercq / Temperley',license='CC BY 4.0 (corpus transcription)',sourceFile=entry['sourceFile'],sourceSha256=hashlib.sha256(raw).hexdigest(),sourceUrl='https://rockcorpus.midside.com/melodic_transcriptions.html',form='vocal-melody-estimated-offsets',articulation='Estimated offsets: min(one bar, next onset); original onset timings preserved.')

def main():
    parser=argparse.ArgumentParser();parser.add_argument('archive');args=parser.parse_args()
    root=Path(__file__).resolve().parents[1];manifest=json.loads((root/'ROCK_050_SOURCES.json').read_text());bank=[]
    with zipfile.ZipFile(args.archive) as z:
        for entry in manifest['tracks']:
            raw=z.read(entry['sourceFile']);assert hashlib.sha256(raw).hexdigest()==entry['sha256'];bank.append(convert(raw,entry))
    assert len(bank)==50 and len({m['id'] for m in bank})==50
    (root/'rock-melodies.mjs').write_text('// Generated by tools/import_rock_melodies.py; see MELODY_CATALOG_SOURCES.md.\nexport const ROCK_MELODIES='+json.dumps(bank,ensure_ascii=False,separators=(',',':'))+';\n')
    print(f'Imported {len(bank)} rock vocal melodies; exact source MIDI/onsets verified, estimated note offsets.')
if __name__=='__main__':main()
