// UI language is device-local. Musical symbols and style names stay unchanged.
const pairs=[
['Перетаскивай корабль по полю или управляй стрелками. Ответы — кнопки под полем.','Drag the ship or use arrow keys. Answer with the buttons below.'],['Игровое поле','Flight field'],['Музыкальное оружие','Musical weapons'],['Прогресс сектора','Sector progress'],['Последняя распознанная цифровка','Last recognized chord symbol'],['Повторить тонику и сигнал','Replay tonic and signal'],['Повторить звучание — пробел','Replay sound — Space'],['начало','home'],
['Ангар кораблей','Ship hangar'],['Инженерия звука','Engineering sound'],['Четыре машины. Нажми изображение, чтобы открыть оригинал.','Four machines. Tap an image to open the original.'],['Полёт на паузе · выбери стиль или партию, чтобы вернуться','Flight paused · identify the style or part to return'],['РИТМ-КОМНАТА','RHYTHM ROOM'],['Узнай стиль или партию — вернись в полёт','Identify the style or part to resume flight'],
['Сначала познакомимся со звуками.','First, explore the sounds.'],['Услышь I и V','Recognize I and V'],['Сначала звучит тоника I, потом сигнал гидры. Узнай: это I или V?','First hear tonic I, then the enemy signal. Is it I or V?'],['Во время сигнала гидра не атакует. Тяни корабль пальцем; правильная кнопка заряжает выстрел.','The enemy waits while the signal plays. Drag the ship; the correct button powers your shot.'],['Корень + тип аккорда','Root + chord quality'],['Верхний блок оружия — ступень корня. Нижний — точный тип аккорда: maj, 6, m7 или 7sus4. Пробивай щиты в любом порядке.','Select a root degree and an exact chord quality: maj, 6, m7 or 7sus4. Break the shields in either order.'],['Бас даёт усиление сразу. Два пробитых щита уничтожают гидру. Ошибка не восстанавливает уже пробитый щит.','Recognizing the root powers your weapon immediately. Break both shields to neutralize the ship. A mistake does not restore a broken shield.'],
['Вся хроматика. Точная цифровка.','All chromatic roots. Exact chord symbols.'],['12 корней × 22 типа аккорда. Например: ♭IImaj7 или IIIm7. Типы оружия переключаются вкладками «Аккорды» / «Альтерации».','12 roots × 22 chord qualities. For example, ♭IImaj7 or IIIm7. Switch quality banks with Chords / Alterations.'],['Альтерации','Alterations'],['ДВОЙНОЙ ЩИТ','DUAL SHIELD'],['ХРОМАТИЧЕСКИЙ ПОЛЁТ','CHROMATIC FLIGHT'],['ПЕРЕПРАВА','CROSSING'],['Корень и точный тип — в любом порядке','Root and exact quality — either order'],['Корень + тип → цифровка','Root + quality → chord symbol'],
['Ровные восьмые; малый барабан на 2 и 4.','Straight eighths; snare on beats 2 and 4.'],['Длинная и короткая доли в каждой паре; устойчивый бэкбит.','Long-short pairs with a steady backbeat.'],['Рисунок ride: пульс и короткая нота перед следующей долей.','Ride pattern: a steady pulse and a short pickup into the next beat.'],['Пять ударов: три в первом такте, два во втором.','Five strokes: three in bar one, two in bar two.'],['Пять ударов: два в первом такте, три во втором.','Five strokes: two in bar one, three in bar two.'],['Ровные восьмые, синкопированный обод и мягкая басовая опора.','Straight eighths, syncopated rim and soft bass support.'],['Синкопы бас-барабана между основными долями.','Syncopated kick between the main beats.'],['One drop: бас и обод на третьей доле такта.','One drop: kick and rim on beat three.'],['Бас-барабан на каждой доле, открытый рисунок между долями.','Kick on every beat with offbeat hi-hat.'],['Три доли в такте; свинговое движение ride.','Three beats per bar with a swung ride pattern.'],['Учебный Mambo: синкопированный верхний рисунок и басовая опора.','Mambo study: syncopated upper pattern and bass support.'],['Учебный Calypso: ровный шаг и синкопированный рисунок между долями.','Calypso study: a steady step and syncopated offbeat pattern.'],['Семь ударов колокольчика внутри двенадцати подразделений. Четыре крупных пульса.','Seven bell strokes across twelve subdivisions, with four main pulses.'],['Третий удар трёхударной стороны на полдоли позже, чем в Son Clave.','The third stroke on the three-stroke side is half a beat later than Son Clave.'],['Учебный Cha-cha-cha: ровный верхний пульс и дробный ответ обода.','Cha-cha-cha study: steady bell pulse with a busier rim response.'],['Учебная Samba: повторяющаяся короткая пара басовых ударов и синкопы сверху.','Samba study: repeating close kick pairs with upper syncopation.'],['Басовая партия Tumbao: синкопированные опоры, оставляющие первую долю пустой. Это партия, а не весь стиль.','Tumbao bass part: syncopated support leaving beat one empty. This is a part, not a complete style.'],['Клавишная партия Montuno: повторяющийся синкопированный аккордовый рисунок. Это партия, а не весь стиль.','Montuno keyboard part: a repeating syncopated chord pattern. This is a part, not a complete style.'],['Учебный Charleston: характерная пара атак на 1 и «и» второй доли.','Charleston study: the characteristic attacks on beat one and the upbeat of two.'],['Учебный Rock ’n’ Roll: шаффл, бэкбит и движущийся басовый рисунок.','Rock ’n’ Roll study: shuffle, backbeat and a moving bass figure.'],
['Ознакомление со звуками','Sound library'],['СЛУХОВОЙ АНГАР · БЕЗ ТАЙМЕРА','SOUND HANGAR · NO TIMER'],
['Тот же синтезатор, что в полёте. Нажми символ, чтобы услышать его. Сравни maj → maj7 → 7: у двух последних добавлена разная септима.','The same synth as in flight. Tap a symbol to hear it. Compare maj → maj7 → 7: the last two add different sevenths.'],
['Один интервал — одна цифра. Ошибка завершает попытку','One interval, one token. A wrong pickup ends the attempt'],
['Один интервал — один жетон.','One interval, one token.'],['Слушай. Лови. Усиливайся.','Listen. Catch. Power up.'],
['Магистр музыки','Master of Music'],['Херби Хэнкок','Herbie Hancock'],['Новичок','Beginner'],['Студент','Student'],
['I и V · спокойный полёт · помощь','I and V · gentle flight · guidance'],['Два щита · основные аккорды','Two shields · core chords'],['12 корней · 22 типа · все интервалы','12 roots · 22 qualities · all intervals'],['Вся гармония · быстрые враги · узкие проходы','Full harmony · fast enemies · narrow passages'],
['Лови звуки. Обходи скалы.','Catch sounds. Navigate the rocks.'],['Пробивай путь к своей музыке.','Find your way to your music.'],
['Послушать новые сигналы','Learn the new signals'],['Сразу в бой','Start flight'],['Артефакты и правила','Artifacts and rules'],['ПАМЯТКА ПИЛОТА','PILOT GUIDE'],
['Продолжить полёт','Resume flight'],['Выбрать уровень','Choose difficulty'],['На базу','Back to base'],['Вернуться','Back'],['Повторить','Replay'],['Послушать ещё','Listen again'],['Слушать','Listen'],['Слушай','Listen'],['Запомнил','Got it'],['В бой','Fly'],
['Аккорды','Chords'],['Интервалы','Intervals'],['Полиритмы','Polyrhythms'],['Ритмы','Rhythms'],['Вместе','Together'],['Вверх','Up'],['Вниз','Down'],['По кругу','Loop'],['Оба слоя','Both layers'],['Высокий','High'],['Низкий','Low'],['Стоп','Stop'],['Остановлено','Stopped'],
['Повтори или выбери другой символ для сравнения','Replay or choose another symbol to compare'],['Интервал от одного опорного звука','Interval from one reference pitch'],['сначала сравни слои отдельно','compare the separate layers first'],['высоких ударов против','high hits against'],['низких за один общий цикл','low hits in one shared cycle'],['В игре с уровня','Available in flight from'],['в игре с уровня','available in flight from'],['Корень C3 · выбери звук','Root C3 · choose a sound'],['корень C3','root C3'],['слушай рисунок','listen to the pattern'],
['мажорное трезвучие','major triad'],['минорное трезвучие','minor triad'],['большой мажорный септаккорд','major seventh chord'],['доминантсептаккорд','dominant seventh chord'],['минорный септаккорд','minor seventh chord'],['мажорный с секстой','major sixth'],['минорный с секстой','minor sixth'],['полууменьшённый','half diminished'],['уменьшённый септаккорд','diminished seventh'],['септаккорд с задержанием','suspended seventh'],['увеличенное трезвучие','augmented triad'],['малая терция','minor third'],['большая терция','major third'],['чистая квинта','perfect fifth'],['малая септима','minor seventh'],['большая септима','major seventh'],
['Подсказка','Hint'],['Использовать подсказку','Use a hint'],['Как играть','How to play'],['Пауза','Pause'],['ПАУЗА','PAUSED'],['Держим позицию.','Holding position.'],['Включи звук · наушники помогут','Enable audio · headphones help'],['рекорд','best'],['ЩИТ КОРАБЛЯ','SHIP SHIELD'],['Щит:','Shield:'],['из 5','of 5'],['СЕКТОР','SECTOR'],['ЛУНА','MOON'],['МАРС','MARS'],['МАЯК','BEACON'],['Готовимся к полёту','Preparing for flight'],['Ожидание пилота','Waiting for pilot'],
['СОБЕРИ ИНТЕРВАЛ','CATCH THE INTERVAL'],['ВЫСОКИЙ : НИЗКИЙ','HIGH : LOW'],['УЗНАЙ СИГНАЛ — ВЫСТРЕЛИ','IDENTIFY THE SIGNAL — FIRE'],['ВЫБЕРИ СИГНАЛ — ВЫСТРЕЛИ','CHOOSE THE SIGNAL — FIRE'],['ДВА ЩИТА · ДВА ВИДА ОРУЖИЯ','TWO SHIELDS · TWO WEAPONS'],['Ступень','Degree'],['Тип','Quality'],['БАС','ROOT'],['ТИП','QUALITY'],['ИМПУЛЬС','PULSE'],['КОМБО','COMBO'],['РАЗГОН · ВЕЕРНЫЙ ОГОНЬ','BOOST · SPREAD FIRE'],
['Выбери ступень относительно тоники I','Choose a degree relative to tonic I'],['Узнай сигнал и стреляй','Identify the signal and fire'],['Пробей оба щита','Break both shields'],['Поймай цифру услышанного интервала','Catch the token for the interval you heard'],['Узнай на слух','Identify by ear'],['Выбери услышанное','Choose what you heard'],['Слушай артефакт','Listen to the artifact'],['Слушай опору','Listen to the tonic'],['тоника — точка отсчёта','tonic — your reference'],['Сигнал гидры','Enemy signal'],['Слушай тип аккорда','Listen to the chord quality'],
['Попытка потеряна · нужно','Attempt lost · correct token:'],['Время вышло · попробуем ещё','Time is up · try again'],['Выбрано','Selected'],['звучит','playing'],['Звучит','Playing'],['нейтрализованы','neutralized'],['нейтрализуются','are neutralized'],['учителя','teachers'],['учитель атакует','teacher approaching'],['Литература','Literature'],['Математика','Mathematics'],['Химия','Chemistry'],['Физ-ра','PE'],['НВП','Civil defense'],['силы','energy'],['Щит задет · продолжай полёт','Shield hit · keep flying'],['Щит пробит','Shield broken'],['щиты пробиты','shields broken'],['тип распознан','quality identified'],['Тяни корабль · стрельба автоматическая','Drag to fly · automatic fire'],['Попробовать сбор интервалов','Try interval tokens'],['Попробовать','Try'],['Сигнал:','Signal:'],['Тип аккорда:','Chord quality:'],['тоника','tonic'],['пятая','fifth'],['четвёртая','fourth'],['третья','third'],['вторая','second'],['шестая','sixth'],['седьмая','seventh'],['РАЗВЕДЧИК','SCOUT'],['КОРВЕТ','CORVETTE'],['КРЕЙСЕР','CRUISER'],['КРЕПОСТЬ','FORTRESS'],
['Тренажёр ступеней и аккордов','Degree and chord trainer'],['ТРЕНАЖЁР · БЕЗ ВРАГОВ И ТАЙМЕРА','TRAINER · NO ENEMIES OR TIMER'],['Слуховой полигон','Ear training range'],['Звучание такое же, как в полёте. Ступень можно услышать вверх или вниз: ответ всегда обозначает расстояние от тоники. У аккордов меняется направление звучания, а тип остаётся тем же.','The sound is the same as in flight. A degree may play upward or downward; the answer always names its distance from the tonic. Chord direction changes, but its quality does not.'],['Ступени','Degrees'],['Нажми вариант ответа','Choose an answer'],['Пока нет ответов','No answers yet'],['верно','correct'],['направление:','direction:'],['восходящее','ascending'],['нисходящее','descending'],['одновременно','together'],['Следующий сигнал','Next signal'],['Точный слуховой захват','Accurate ear catch'],['Сверь обозначение и послушай ещё','Check the symbol and listen again'],['Верный ответ:','Correct answer:'],['точно!','exact!'],
['Квартет вышел на поле · полёт удержан, выбери стиль или партию','The quartet has arrived on the field · flight is held while you identify the style or part'],['РИТМ-ПАУЗА · КВАРТЕТ НА ПОЛЕ','RHYTHM PAUSE · QUARTET ON FIELD'],['Узнай стиль или партию — и продолжим тот же полёт','Identify the style or part, then resume this flight'],
];
export function installLanguage(){
  if(typeof MutationObserver==='undefined')return;
  let language='ru';try{language=localStorage.getItem('ear-game-language')==='en'?'en':'ru';}catch{}
  const originals=new WeakMap(),attributes=new WeakMap(),button=document.getElementById('language');
  const ordered=[...pairs].sort((a,b)=>b[0].length-a[0].length);
  const translate=text=>{for(const [ru,en] of ordered)text=text.split(ru).join(en);return text;};
  function apply(){
    observer.disconnect();document.documentElement.lang=language;
    const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);let node;
    while((node=walker.nextNode())){if(['SCRIPT','STYLE'].includes(node.parentElement?.tagName))continue;const old=originals.get(node);const raw=old&&node.nodeValue===old.rendered?old.raw:node.nodeValue;const rendered=language==='en'?translate(raw):raw;if(node.nodeValue!==rendered)node.nodeValue=rendered;originals.set(node,{raw,rendered});}
    for(const el of document.querySelectorAll('[aria-label],[title]')){if(el===button)continue;const saved=attributes.get(el)||{};for(const key of ['aria-label','title']){if(!el.hasAttribute(key))continue;const value=el.getAttribute(key),old=saved[key],raw=old&&old.rendered===value?old.raw:value,rendered=language==='en'?translate(raw):raw;if(value!==rendered)el.setAttribute(key,rendered);saved[key]={raw,rendered};}attributes.set(el,saved);}
    button.textContent=language==='ru'?'RU / EN':'EN / RU';button.setAttribute('aria-label',language==='ru'?'Switch to English':'Переключить на русский');
    observer.observe(document.body,{subtree:true,childList:true,characterData:true});
  }
  const observer=new MutationObserver(apply);button.addEventListener('click',()=>{language=language==='ru'?'en':'ru';try{localStorage.setItem('ear-game-language',language);}catch{}apply();});apply();
}
